import type { Metadata } from "next";
import { Lexend_Tera } from "next/font/google"
import "./globals.css";

const lexendTera = Lexend_Tera({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${lexendTera.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
